HardwareSerial: Fix secondary serial interface
NUM_SERIAL wasn't defined prior to this commit, and because of that,
using Serial1 would cause compilation to abort with error:
"'Serial1' was not declared in this scope"